### ISSUE TITLE
Fixed view width

### ISSUE THREAD

**Issue by jk** [enormego/cocoa-helpers#1]
There's an issue in UITableView/UITableViewHelper.m:36 with 

```
UITableViewUpdatingView* view = [[UITableViewUpdatingView alloc] initWithFrame:CGRectMake((int)((self.frame.size.width-130.0f)/2), UPDATING_OFFSET_Y, 130.0f, 42.0f) title:title];
```

When you're not on an english system and the localized string is wider than »Updating...« (in german it's for example »Aktualisieren…«) the overlay view gets messed up. This because of the fixed width here of 130.0f.

**Comment by enormego** [comment]
This was fixed in commit 0007099.
